### ISSUE TITLE
Data Unreachable.

### ISSUE THREAD

**Issue by theodore-zxd** [simlocmatch/simlocmatch-benchmark#1]
Dear Sir,

We found the link in _prepare_data.sh_ is not reachable. 

https://imperialcollegelondon.box.com/shared/static/48w09bdd5n763qdp7ph5352cwnfqaan4.xz

Is everything ok with the server? Thanks very much.

Yours sincerely,
Theodore

**Comment by vbalnt** [comment]
Hi, I have tested the link and it seems to work fine, are you sure nothing else is blocking access to this?

**Comment by theodore-zxd** [comment]
Thanks. You are right. After we cancel the blocking, this file is accessable.
