### ISSUE TITLE
submission

### ISSUE THREAD

**Issue by superluckyxhh** [simlocmatch/simlocmatch-benchmark#7]
Hello, I submitted the result on June 3rd, why can't I see it now? When the result will be available after the submission? my id：nanxiaohu18@mails.ucas.ac.cn

**Comment by vbalnt** [comment]
This probably means the submission failed - are you sure the format is correct?

Can you verify/compare with the provided examples in the `/methods` folder?

**Comment by superluckyxhh** [comment]
Yes, I submit 2 version: one is provided examples "ORB.h5", another is "SPG.h5"，None of the results show up.

**Comment by vbalnt** [comment]
There are no such uploads as far as I can see. I'll follow up via email. 
Are you sure that the files are getting uploaded correctly?
