### ISSUE TITLE
submission 

### ISSUE THREAD

**Issue by superluckyxhh** [simlocmatch/simlocmatch-benchmark#8]
Hi. I receive your email yesterday. 
I reply you but the email was returned(It's probably blocked by the firewall or something).So I can only communicate with you by github. 
I reply your questions: 1.I'm sure upload successful. I got the message "Method submitted. Please be patient.....";2.I use nanxiaohu18@mails.ucas.ac.cn to register the Challenge. 
I have two questions:1.until now, I find only two official methods in image matching public leaderboard. Is the true case? or something blocked by firewall? 2. If I can't upload by website, other submit ways I can choose?
Thank you

**Comment by ducha-aiki** [comment]
Have you checked "My submissions" link once you logged-in? Submissions here are not showing on the public leaderboard until you allow it.

**Comment by tsattler** [comment]
I had also uploaded two files with results (Colmap's SIFT and D2-Net), unfortunately, they do not show up under "my submissions".

**Comment by vbalnt** [comment]
Hi @Nanxiaohu666 - unfortunately I dont see any submissions under this email - can you please double check that the upload is working as expected? You should see the uploading bar going slowly up. If your submission is big, it might take some time (~10mins) to upload.

**Comment by vbalnt** [comment]
@tsattler - I see an error in the format of submission keys - will follow up with you.

**Comment by vbalnt** [comment]
@Nanxiaohu666 have you made an account with that email? if yes, I can manually trigger the eval method if you find another way to get the h5 files to me. Thanks

**Comment by ducha-aiki** [comment]
@vbalnt I have a problem with appearing some of me last submissions as well. I first thought that they are just too big, but then I saw PDCNet_multiscale, which is of a similar size.

**Updated**: it appeared now :)

**Comment by vbalnt** [comment]
I suspect that due to the fact that lots of submissions arrived, the server had a bit of a backlog :)
