### ISSUE TITLE
What is matching success rate?

### ISSUE THREAD

**Issue by jiangwei221** [simlocmatch/simlocmatch-benchmark#9]
Hi SimLoc team:

Do you mind provide some details about the matching success rate? and how to compute it?
(Or will it be released close to the DDL?)

Thanks!

**Comment by jiangwei221** [comment]
Is it similar to inlier ratio? (just a guess)

**Comment by vbalnt** [comment]
Hi! 

we will release more details soon but for a quick overview:

- Matching success rate: Number of correct matches / number of all provided matches. It is indeed similar to inlier ratio - but in this case the "inliers" are true inliers (i.e pixel-wise matching GT from the synthetic models)
